### ISSUE TITLE
bwd_depth error

### ISSUE THREAD

**Issue by AnudhinaDhanabalan** [SJoJoK/3DGStream#17]
File "train_frames.py", line 291, in train_one_frame
    s1_ress, s2_ress, pre_time, s1_time, s2_time = training_one_frame(lp.extract(args), op.extract(args), pp.extract(args), args.load_iteration, args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train_frames.py", line 84, in training_one_frame
    render_pkg = render(viewpoint_cam, gaussians, pipe, background)
  File "/home/arrstudios/Desktop/AI/3DGStream/gaussian_renderer/__init__.py", line 49, in render
    bwd_depth=pipe.bwd_depth
TypeError: __new__() got an unexpected keyword argument 'bwd_depth'

**Comment by SJoJoK** [comment]
It seems that you didn't reinstall the submodules/diff-gaussian-rasterization by running `pip install submodules/diff-gaussian-rasterization`

**Comment by AnudhinaDhanabalan** [comment]
Traceback (most recent call last):
  File "train_frames.py", line 377, in <module>
    train_frames(lp,op,pp,args)
  File "train_frames.py", line 335, in train_frames
    train_one_frame(lp,op,pp,args)
  File "train_frames.py", line 291, in train_one_frame
    s1_ress, s2_ress, pre_time, s1_time, s2_time = training_one_frame(lp.extract(args), op.extract(args), pp.extract(args), args.load_iteration, args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train_frames.py", line 84, in training_one_frame
    render_pkg = render(viewpoint_cam, gaussians, pipe, background)
  File "/home/arrstudios/Desktop/AI/3DGStream/gaussian_renderer/__init__.py", line 49, in render
    bwd_depth=pipe.bwd_depth
TypeError: __new__() got an unexpected keyword argument 'bwd_depth'

**Comment by AnudhinaDhanabalan** [comment]
still having the same issue

**Comment by SJoJoK** [comment]
This issue arises because you use the wrong/old `diff_gaussian_rasterization`. Please check your diff_gaussian_rasterization/\_\_init\_\_.py. The diff_gaussian_rasterization used in this repo is https://github.com/SJoJoK/3DGStreamRasterizer/tree/39b62ce5fcd1bda46b04c0f93037a1aa85216925/diff_gaussian_rasterization, not the one from the origin gaussian-splatting repo. If you install submodules/diff-gaussian-rasterization correctly, the  `diff_gaussian_rasterization` that used in this code will be the modified/new one.

**Comment by AnudhinaDhanabalan** [comment]
ERROR: Could not find a version that satisfies the requirement 3DGStreamRasterizer (from versions: none)
ERROR: No matching distribution found for 3DGStreamRasterizer
 i am getting this error while installing what you said

**Comment by SJoJoK** [comment]
I'm not going to discuss the installation of the pip package in the issue because this is not related to our research codes. If you don't know how to use pip to install a local package and don't know how submodules of git works. I suggest you create a new environment with necessary packages, then use `git clone https://github.com/SJoJoK/3DGStream.git —recursive`, and then use `pip install submodules/diff-gaussian-rasterization`
