### ISSUE TITLE
Blurry rendered images in the viewer

### ISSUE THREAD

**Issue by dlazares** [SJoJoK/3DGStream#4]
Hi I got the viewer up and running. The video starts very clear off the initial ply but seems to get blurry and fall apart as time progresses forwards. In the paper, you report seeing a good average PSNR across the sequence so I'm wondering if something is wrong on the viewer side?
here's an example on one of the later frames in the video
![save](https://github.com/SJoJoK/3DGStream/assets/10122282/a4ab903b-32b4-4c95-8c74-7c7b4d1ba844)

**Comment by SJoJoK** [comment]
Hello, thanks for your interest in our work. Because the viewer we provide is only a toy demo without a good programming, at present, it can only guarantee good results by follow the steps provided in the README exactly(that is, no robustness😢).

If you get such a result while accurately following our steps, I can provide a viewer screen recording in the next few days.

Thanks.

**Comment by SJoJoK** [comment]
Hello @dlazares, I capture a video by my phone (I'm not familiar with the OBS Studio, so the quality of the screen recording is low) to show how to use the viewer, please check the attached video. 
Please let me know if you follow step shows in the videos but still get buggy renderings, it may due to I uploaded the wrong files in the Google Drive.
Thanks.

https://github.com/SJoJoK/3DGStream/assets/50450335/033493a4-8967-49a4-be00-377a2d02b4c9

**Comment by dlazares** [comment]
It may be wrong files in Google drive since I did the steps you did

**Comment by SJoJoK** [comment]
Ok, I will upload the correct in recent working days.

**Comment by SJoJoK** [comment]
Hello @dlazares , I've just downloaded the FVV that I previously uploaded to Google Drive. It works well with the viewer, so I think the problem might be due to the mismatch of the environment or something else.

Here's some information of my machine, FYI:
* OS: Windows 11
* GPU: RTX 2060
* Driver: 531.87 
* CUDA: 12.1
* Python: 3.10
* Pytorch: 2.1.1+cu121
* tinycudann: 17

Besides, I test the viewer and the FVV in another machine (Actually, the FVV is constructed/trained on this machine), and it also works well. Here's the information of it:
 
* OS: Ubuntu 22.04
* GPU: RTX A6000
* Driver: 535.86.05
* CUDA: 11.8
* Python: 3.8
* Pytorch: 2.0.1+cu118
* tinycudann: 1.7

**Comment by dlazares** [comment]
hmmm.... my setup is similar to your first one except I'm running on Windows Subystem for Linux and am using a 4090.

**Comment by SJoJoK** [comment]
The driver's version might be the reason since the NTC is implemented by tinycudann, a GPU/Driver related module. The wrong output of NTC will make the scene deform incorrectly. As the error of deformation accumulates, the latter frames will be buggy.

Since the implementation of the viewer is quite simple and I've tested it on different machines, I think rendering process of the viewer is bug-free. Thus, the reason of your buggy rendering can only due to the wrong output of the NTC (In your image, the additional 3dgs is rendered correctly). Upon the release of our training code, you can construct your own FVV (init_3dgs, NTCs and additional_3dgs) and render it by the viewer, as the correctness of the NTC have been validated in your training process.

**Comment by dlazares** [comment]
Sounds good, I'll give it a try when the training code is up.
